import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Topo from "./components/Topo";
import Banner from "./components/Banner";
import Produtos from "./components/SecaoProdutos";
import Sobre from "./components/Sobre";
import Contato from "./components/Contato";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topo/>
      <section>
        <Banner/>
      </section>
      <section>
        <Produtos/>
      </section>
      <section>
        <Sobre/>
      </section>
      <section>
        <Contato/>
      </section>
    </>
  );
}
